apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: semantic-cache
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: proxy
          image: ghcr.io/izhan05803/semantic-cache-proxy:main
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: proxy-config
            - secretRef:
                name: proxy-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
