apiVersion: v1
kind: Secret
metadata:
  name: indexer-secret
  namespace: semantic-cache
type: Opaque
stringData:
  INDEXER_API_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
  namespace: semantic-cache
type: Opaque
stringData:
  INDEXER_API_KEY: ""
  GOOGLE_API_KEY: ""
