# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cache_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x61\x63he_service.proto\x12\x05\x63\x61\x63he\"<\n\x0c\x43\x61\x63heRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x1c\n\x14similarity_threshold\x18\x02 \x01(\x02\"=\n\rCacheResponse\x12\x0b\n\x03hit\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"\x90\x01\n\tCacheData\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x30\n\x08metadata\x18\x03 \x03(\x0b\x32\x1e.cache.CacheData.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x7f\n\x0c\x43\x61\x63heService\x12\x37\n\nCheckCache\x12\x13.cache.CacheRequest\x1a\x14.cache.CacheResponse\x12\x36\n\x0bUpdateCache\x12\x10.cache.CacheData\x1a\x15.cache.UpdateResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_CACHEDATA_METADATAENTRY']._loaded_options = None
  _globals['_CACHEDATA_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CACHEREQUEST']._serialized_start=30
  _globals['_CACHEREQUEST']._serialized_end=90
  _globals['_CACHERESPONSE']._serialized_start=92
  _globals['_CACHERESPONSE']._serialized_end=153
  _globals['_CACHEDATA']._serialized_start=156
  _globals['_CACHEDATA']._serialized_end=300
  _globals['_CACHEDATA_METADATAENTRY']._serialized_start=253
  _globals['_CACHEDATA_METADATAENTRY']._serialized_end=300
  _globals['_UPDATERESPONSE']._serialized_start=302
  _globals['_UPDATERESPONSE']._serialized_end=335
  _globals['_CACHESERVICE']._serialized_start=337
  _globals['_CACHESERVICE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
