// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: semantic-cache/proto/cache_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Prompt              string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SimilarityThreshold float32                `protobuf:"fixed32,2,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"` // e.g., 0.85
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_cache_service_proto_rawDescGZIP(), []int{0}
}

func (x *CacheRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CacheRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

type CacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"` // The similarity score found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_cache_service_proto_rawDescGZIP(), []int{1}
}

func (x *CacheResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *CacheResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *CacheResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CacheData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // For extra info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheData) Reset() {
	*x = CacheData{}
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheData) ProtoMessage() {}

func (x *CacheData) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheData.ProtoReflect.Descriptor instead.
func (*CacheData) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_cache_service_proto_rawDescGZIP(), []int{2}
}

func (x *CacheData) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CacheData) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *CacheData) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_cache_proto_cache_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_semantic_cache_proto_cache_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_semantic_cache_proto_cache_service_proto protoreflect.FileDescriptor

const file_semantic_cache_proto_cache_service_proto_rawDesc = "" +
	"\n" +
	"(semantic-cache/proto/cache_service.proto\x12\x05cache\"Y\n" +
	"\fCacheRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x121\n" +
	"\x14similarity_threshold\x18\x02 \x01(\x02R\x13similarityThreshold\"S\n" +
	"\rCacheResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"\xb8\x01\n" +
	"\tCacheData\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12:\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1e.cache.CacheData.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x7f\n" +
	"\fCacheService\x127\n" +
	"\n" +
	"CheckCache\x12\x13.cache.CacheRequest\x1a\x14.cache.CacheResponse\x126\n" +
	"\vUpdateCache\x12\x10.cache.CacheData\x1a\x15.cache.UpdateResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_semantic_cache_proto_cache_service_proto_rawDescOnce sync.Once
	file_semantic_cache_proto_cache_service_proto_rawDescData []byte
)

func file_semantic_cache_proto_cache_service_proto_rawDescGZIP() []byte {
	file_semantic_cache_proto_cache_service_proto_rawDescOnce.Do(func() {
		file_semantic_cache_proto_cache_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_semantic_cache_proto_cache_service_proto_rawDesc), len(file_semantic_cache_proto_cache_service_proto_rawDesc)))
	})
	return file_semantic_cache_proto_cache_service_proto_rawDescData
}

var file_semantic_cache_proto_cache_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_semantic_cache_proto_cache_service_proto_goTypes = []any{
	(*CacheRequest)(nil),   // 0: cache.CacheRequest
	(*CacheResponse)(nil),  // 1: cache.CacheResponse
	(*CacheData)(nil),      // 2: cache.CacheData
	(*UpdateResponse)(nil), // 3: cache.UpdateResponse
	nil,                    // 4: cache.CacheData.MetadataEntry
}
var file_semantic_cache_proto_cache_service_proto_depIdxs = []int32{
	4, // 0: cache.CacheData.metadata:type_name -> cache.CacheData.MetadataEntry
	0, // 1: cache.CacheService.CheckCache:input_type -> cache.CacheRequest
	2, // 2: cache.CacheService.UpdateCache:input_type -> cache.CacheData
	1, // 3: cache.CacheService.CheckCache:output_type -> cache.CacheResponse
	3, // 4: cache.CacheService.UpdateCache:output_type -> cache.UpdateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_semantic_cache_proto_cache_service_proto_init() }
func file_semantic_cache_proto_cache_service_proto_init() {
	if File_semantic_cache_proto_cache_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_semantic_cache_proto_cache_service_proto_rawDesc), len(file_semantic_cache_proto_cache_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_semantic_cache_proto_cache_service_proto_goTypes,
		DependencyIndexes: file_semantic_cache_proto_cache_service_proto_depIdxs,
		MessageInfos:      file_semantic_cache_proto_cache_service_proto_msgTypes,
	}.Build()
	File_semantic_cache_proto_cache_service_proto = out.File
	file_semantic_cache_proto_cache_service_proto_goTypes = nil
	file_semantic_cache_proto_cache_service_proto_depIdxs = nil
}
